#!/bin/bash
# Quick Netlify Manual Deployment Script

echo "🚀 ORGANIC FUEL - NETLIFY MANUAL DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ GitHub Repository Created:"
echo "   https://github.com/solutionspma/organic-fuel-crm"
echo ""
echo "✅ Code Pushed to GitHub"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 NEXT STEPS - MANUAL NETLIFY SETUP:"
echo ""
echo "1. Go to Netlify Dashboard:"
echo "   https://app.netlify.com"
echo ""
echo "2. Click: 'Add new site' → 'Import an existing project'"
echo ""
echo "3. Choose: GitHub"
echo ""
echo "4. Select repository: solutionspma/organic-fuel-crm"
echo ""
echo "5. Build settings:"
echo "   • Build command: (leave empty)"
echo "   • Publish directory: public"
echo "   • Functions directory: netlify/functions"
echo ""
echo "6. Click 'Deploy site'"
echo ""
echo "7. After deployment, add Environment Variables:"
echo "   Site settings → Environment variables → Add variables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔐 ENVIRONMENT VARIABLES TO ADD:"
echo ""
echo "SUPABASE_URL=https://hkfcfooyqaonbszhnrpx.supabase.co"
echo "SUPABASE_SERVICE_ROLE_KEY=[get from Supabase]"
echo ""
echo "TELNYX_API_KEY=[your Telnyx API key]"
echo "TELNYX_FROM_NUMBER=+18663371932"
echo ""
echo "NOTIFY_SMS_1=+12252485772"
echo "NOTIFY_SMS_2=+12254188858"
echo ""
echo "NOTIFY_EMAIL_PRIMARY=kplenty@gmail.com"
echo "NOTIFY_EMAIL_CC=solutions@pitchmarketing.agency"
echo ""
echo "PEXELS_API_KEY=RH8RBXiR6FvHEKqhKz6t6BQqGQHLJc4eXgNQq5oPd9FVVSJlTuzhAWvV"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 SUPABASE SETUP:"
echo ""
echo "1. Go to Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/hkfcfooyqaonbszhnrpx/sql/new"
echo ""
echo "2. Copy contents of: supabase/schema.sql"
echo ""
echo "3. Paste and run in SQL Editor"
echo ""
echo "4. Get credentials from: Settings → API"
echo "   • Project URL (already set above)"
echo "   • service_role key → Copy to Netlify env vars"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Opening Netlify Dashboard..."
echo ""

# Open Netlify dashboard
open "https://app.netlify.com"

# Open Supabase dashboard
echo "Opening Supabase Dashboard..."
open "https://supabase.com/dashboard/project/hkfcfooyqaonbszhnrpx"

echo ""
echo "✅ Dashboards opened!"
echo ""
echo "Follow the steps above to complete deployment."
echo ""
